version: '3'


networks:
  my_network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "8001:3306"
    networks:
      - my_network
    volumes:
      # - /home/llopes-d/data/database:/var/lib/mysql
      - /Users/user/Documents/data/database:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      # - /home/llopes-d/data/frontend:/var/www/html
      - /Users/user/Documents/data/frontend:/var/www/html
    ports:
      - "8000:443"
    # network_mode: bridge
    networks:        # Adicionando a seção de redes
      - my_network  
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      # - /home/llopes-d/data/frontend:/var/www/html
      - /Users/user/Documents/data/frontend:/var/www/html
    ports:
      - "8002:9000"
    # network_mode: bridge
    networks:        # Adicionando a seção de redes
      - my_network  