version: '3'

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes: ["${DB_VOLUME}:/var/lib/mysql"]
    networks: [inception]
    env_file: [.env]

  nginx:
    container_name: nginx
    build: requirements/nginx/
    volumes: ["${FRONTEND_VOLUME}:/var/www/html"]
    depends_on: [wordpress]
    networks: [inception]
    ports: [443:443]

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    volumes: ["${FRONTEND_VOLUME}:/var/www/html"]
    networks: [inception]
    depends_on: [mariadb]
    env_file: [.env]

## BONUS PART
  # ftp:
  #   container_name: ftp
  #   image: ftp:latest
  #   build: requirements/bonus/ftp/
  #   volumes:
  #     # - /home/llopes-d/data/frontend:/var/www/html
  #     - /Users/user/Documents/data/frontend:/var/www/html
  #   ports:
  #     - "21:21"
  #   networks:
  #     - inception
  #   env_file:
  #     - .env
  # adminer:
  #   container_name: adminer
  #   image: adminer:latest
  #   ports:
  #     - "8080:8080"
  #   build: requirements/bonus/adminer/
  #   networks:
  #     - inception
  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   build: requirements/bonus/redis/
  #   networks:
  #     - inception