version: '3'

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    restart: on-failure
    image: mariadb:latest
    container_name: mariadb
    build: requirements/mariadb/
    volumes: ["${DB_VOLUME}:/var/lib/mysql"]
    networks: [inception]
    env_file: [.env]

  nginx:
    restart: on-failure
    image: nginx:latest
    container_name: nginx
    build: requirements/nginx/
    volumes: ["${FRONTEND_VOLUME}:/var/www/html"]
    depends_on: [wordpress]
    networks: [inception]
    ports: [443:443]

  wordpress:
    restart: on-failure
    image: wordpress:latest
    container_name: wordpress
    build: requirements/wordpress/
    volumes: ["${FRONTEND_VOLUME}:/var/www/html"]
    networks: [inception]
    depends_on: [mariadb]
    env_file: [.env]

## BONUS PART
  ftp:
    restart: on-failure
    image: ftp:latest
    container_name: ftp
    build: requirements/bonus/ftp/
    volumes: ["${FRONTEND_VOLUME}:/var/www/html"]
    networks: [inception]
    env_file: [.env]
    ports: ["21:21", "8000-8030:8000-8030"]

  adminer:
    restart: on-failure
    image: adminer:latest
    container_name: adminer
    build: requirements/bonus/adminer/
    networks: [inception]
    ports: [8080:8080]

  redis:
    restart: on-failure
    image: redis:latest
    container_name: redis
    build: requirements/bonus/redis/
    networks: [inception]