version: '3'


# networks:
#   my_network:
#     driver: bridge


services:
  incep_mariadb:
    image: incep_mariadb:latest
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "8001:3306"
    network_mode: bridge
    volumes:
      - /home/llopes-d/data/database:/var/lib/mysql
  icep_nginx:
    image: incep_nginx:latest
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - /home/llopes-d/data/frontend:/var/www/html
    ports:
      - "8000:443"
    network_mode: bridge
  incep_wordpress:
    image: incep_wordpress:latest
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - /home/llopes-d/data/frontend:/var/www/html
    ports:
      - "8002:9000"
    network_mode: bridge