version: '3'

networks:
  my_network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    networks:
      - my_network
    volumes:
      - /home/llopes-d/data/database:/var/lib/mysql
      # - /Users/user/Documents/data/database:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - /home/llopes-d/data/frontend:/var/www/html
      # - /Users/user/Documents/data/frontend:/var/www/html
    ports:
      - "443:443"
    networks:
      - my_network
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - /home/llopes-d/data/frontend:/var/www/html
      # - /Users/user/Documents/data/frontend:/var/www/html
    networks:
      - my_network
  ftp:
    container_name: ftp
    image: ftp:latest
    build:
      context: requirements/bonus/ftp/
      dockerfile: Dockerfile
    volumes:
      - /home/llopes-d/data/frontend:/var/www/html
    networks:
      - my_network